config/routes.rb
# frozen_string_literal: true

# Como el sitio puede contener puntos, no queremos confundirlos con
# tipos de contenido, por ejemplo que /sites/site.org no intente service
# text/org.
SITE_ID_RE = %r{[^/]+}.freeze

Rails.application.routes.draw do
  devise_for :usuaries, controllers: { registrations: 'registrations' }
  get '/.well-known/change-password', to: redirect('/usuaries/edit')

  require 'que/web'
  mount Que::Web => '/que'

  root 'application#index'

  constraints(Constraints::ApiSubdomain.new) do
    scope module: 'api' do
      namespace :v1 do
        resources :csp_reports, only: %i[create]

        namespace :activity_pub do
          resources :remote_flags, only: %i[show]
        end

        resources :sites, only: %i[index], constraints: { site_id: SITE_ID_RE, id: SITE_ID_RE } do
          get  :'invitades/cookie', to: 'invitades#cookie'
          post :'posts/:layout', to: 'posts#create', as: :posts

          get  :'contact/cookie', to: 'invitades#contact_cookie'
          post :'contact/:form', to: 'contact#receive', as: :contact

          namespace :webhooks do
            post :pull, to: 'pull#pull'

            scope :social_inbox do
              post :moderationqueued, to: 'social_inbox#moderationqueued'
              post :onapproved, to: 'social_inbox#onapproved'
              post :onrejected, to: 'social_inbox#onrejected'
            end
          end
        end
      end
    end
  end

  # Las rutas privadas empiezan con una ruta única para poder hacer un
  # alias en nginx sin tener que usar expresiones regulares para
  # detectar el nombre del sitio.
  get '/sites/private/:site_id(*file)', to: 'private#show', constraints: { site_id: SITE_ID_RE }
  get '/env.js', to: 'env#index'

  match '/api/v3/projects/:site_id/notices' => 'api/v1/notices#create', via: %i[post]

  resources :sites, constraints: { site_id: SITE_ID_RE, id: SITE_ID_RE } do
    # Gestionar actualizaciones del sitio
    get 'pull', to: 'sites#fetch'
    post 'pull', to: 'sites#merge'

    get 'status', to: 'sites#status'
    get 'button', to: 'sites#button'

    # Gestionar usuaries
    get 'usuaries/invite', to: 'usuaries#invite'
    post 'usuaries/invite', to: 'usuaries#send_invitations'
    patch 'usuaries/accept_invitation', to: 'usuaries#accept_invitation'
    patch 'usuaries/reject_invitation', to: 'usuaries#reject_invitation'
    resources :usuaries do
      patch 'demote', to: 'usuaries#demote'
      patch 'promote', to: 'usuaries#promote'
    end

    get 'collaborate', to: 'collaborations#collaborate'
    post 'collaborate', to: 'collaborations#accept_collaboration'

    get 'moderation_queue', to: 'moderation_queue#index'

    resources :instance_moderations, only: [] do
      patch :pause, to: 'instance_moderations#pause'
      patch :allow, to: 'instance_moderations#allow'
      patch :block, to: 'instance_moderations#block'
    end

    patch :instance_moderations_action_on_several, to: 'instance_moderations#action_on_several'
    patch :fediblock_states_action_on_several, to: 'fediblock_states#action_on_several'

    resources :actor_moderations, only: %i[show] do
      ActorModeration.events.each do |actor_event|
        patch actor_event, to: "actor_moderations##{actor_event}"
      end
    end

    patch :actor_moderations_action_on_several, to: 'actor_moderations#action_on_several'

    resources :activity_pub, only: [] do
      ActivityPub.events.each do |event|
        patch event, to: "activity_pubs##{event}"
      end
    end

    patch :activity_pubs_action_on_several, to: 'activity_pubs#action_on_several'

    # Gestionar artículos según idioma
    nested do
      scope '/(:locale)', constraint: /[a-z]{2}(-[A-Z]{2})?/ do
        post :'posts/reorder', to: 'posts#reorder'

        get :'posts/new_array', to: 'posts#new_array'
        get :'posts/new_array_value', to: 'posts#new_array_value'
        get :'posts/new_related_post', to: 'posts#new_related_post'
        get :'posts/new_has_one', to: 'posts#new_has_one'
        get :'posts/form', to: 'posts#form'
        get :'posts/modal', to: 'posts#modal'

        resources :posts do
          get 'p/:page', action: :index, on: :collection
          get :preview, to: 'posts#preview'
        end
      end
    end

    # Gestionar traducciones
    get 'i18n', to: 'i18n#index'
    get 'i18n/edit', to: 'i18n#edit'
    post 'i18n', to: 'i18n#update'

    # Ver límites de tamaño de archivos
    get 'limits', to: 'sites#limits'

    # Compilar el sitio
    post 'enqueue', to: 'sites#enqueue'
    post 'reorder_posts', to: 'sites#reorder_posts'

    resources :stats, only: [:index]
    get :'stats/host', to: 'stats#host'
    get :'stats/uris', to: 'stats#uris'
    get :'stats/resources', to: 'stats#resources'

    resources :build_stats, only: %i[index]
  end
end

app/models/post/indexable.rb
# frozen_string_literal: true

class Post
  # Vuelve indexables a los Posts
  module Indexable
    extend ActiveSupport::Concern

    included do

      # @return [IndexedPost,nil]
      def indexed_post
        site.indexed_posts.find_by_post_id(uuid.value)
      end

      # Devuelve una versión indexable del Post
      #
      # @return [IndexedPost]
      def to_index
        IndexedPost.find_or_initialize_by(post_id: uuid.value, site_id: site.id).tap do |indexed_post|
          indexed_post.layout = layout.name
          indexed_post.path = path.basename
          indexed_post.locale = locale.value
          indexed_post.dictionary = IndexedPost.to_dictionary(locale: locale.value)
          indexed_post.title = title.value
          indexed_post.front_matter = indexable_front_matter
          indexed_post.content = indexable_content
          indexed_post.created_at = date.value
          indexed_post.order = attribute?(:order) ? order.value : 0
        end
      end

      # Indexa o reindexa el Post
      #
      # @return [Boolean]
      def index!
        to_index.save
      end

      def remove_from_index!
        to_index.destroy.destroyed?
      end

      private

      # Los metadatos que se almacenan como objetos JSON.
      #
      # @return [Hash]
      def indexable_front_matter
        {}.tap do |ifm|
          ifm[:usuaries] = usuaries.map(&:id)
          ifm[:draft] = attribute?(:draft) ? draft.value : false

          indexable_attributes.select do |attr|
            self[attr].front_matter?
          end.each do |attr|
            ifm[attr] = self[attr].try(:indexable_values)
          end
        end
      end

      # Devuelve un documento indexable en texto plano
      #
      # XXX: No memoizamos para permitir actualizaciones, aunque
      # probablemente se indexe una sola vez.
      #
      # @return [String]
      def indexable_content
        indexable_attributes.map do |attr|
          self[attr].to_s.tr("\n", ' ')
        end.join("\n").squeeze("\n")
      end

      def indexable_attributes
        @indexable_attributes ||= attributes.select do |attr|
          self[attr].indexable?
        end
      end
    end
  end
end

app/controllers/api/v1/posts_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # Recibe artículos desde colaboraciones anónimas
    class PostsController < ProtectedController
      # Crea un artículo solo si el sitio admite invitades
      def create
        # No procesar nada más si ya se aplicaron todos los filtros
        return if performed?

        usuarie = GitAuthor.new name: 'Anon', email: "anon@#{site.hostname}"
        service = PostService.new(params: params,
                                  site: site,
                                  usuarie: usuarie)

        site.touch if service.create_anonymous.persisted?

        # Redirigir a la URL de agradecimiento
        redirect_to params[:redirect_to] || origin.to_s
      end

      private

      def gave_consent?
        return if params[:consent].present?

        @reason = 'no_consent'
        render plain: Rails.env.production? ? nil : @reason, status: :precondition_required
      end

      def destination_exists?
        return if post? && site.layout?(params[:layout])

        @reason = 'layout_doesnt_exist'
        render plain: Rails.env.production? ? nil : @reason, status: :precondition_required
      end

      def from_is_address?
        true
      end
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# Controlador para artículos
class PostsController < ApplicationController
  include StrongParamsHelper

  before_action :authenticate_usuarie!
  before_action :service_for_direct_upload, only: %i[new edit]

  # TODO: Traer los comunes desde ApplicationController
  breadcrumb -> { current_usuarie.email }, :edit_usuarie_registration_path
  breadcrumb 'sites.index', :sites_path, match: :exact
  breadcrumb -> { site.title }, -> { site_posts_path(site, locale: locale) }, match: :exact

  # Las URLs siempre llevan el idioma actual o el de le usuarie
  def default_url_options
    { locale: locale }
  end

  # @todo Mover a tu propio scope
  def new_array
    @value = pluck_param(:value)
    @name = pluck_param(:name)
    id = pluck_param(:id)

    headers['HX-Trigger-After-Swap'] = 'htmx:resetForm'

    render layout: false
  end

  def new_array_value
    @value = pluck_param(:value)

    render layout: false
  end

  def new_related_post
    @uuid = pluck_param(:value)

    @indexed_post = site.indexed_posts.find_by!(post_id: @uuid)

    render layout: false
  end

  def new_has_one
    @uuid = pluck_param(:value)

    @indexed_post = site.indexed_posts.find_by!(post_id: @uuid)

    render layout: false
  end

  # El formulario de un Post, si pasamos el UUID, estamos editando, sino
  # estamos creando.
  def form
    uuid = pluck_param(:uuid, optional: true)
    locale

    @post =
      if uuid.present?
        site.indexed_posts.find_by!(post_id: uuid).post
      else
        Post.build(site:, locale:, layout: site.layouts[pluck_param(:layout)])
      end

    swap_modals

    render layout: false
  end

  # Genera un modal completo
  #
  # @todo recibir el atributo anterior
  # @param :uuid [String] UUID del post (opcional)
  # @param :layout [String] El layout a cargar (opcional)
  def modal
    uuid = pluck_param(:uuid, optional: true)
    locale

    # @todo hacer que si el uuid no existe se genera un post, para poder
    # pasar el uuid sabiendolo
    @post =
      if uuid.present?
        site.indexed_posts.find_by!(post_id: uuid).post
      else
        Post.build(site:, locale:, layout: site.layouts[pluck_param(:layout)])
      end

    swap_modals

    render layout: false
  end

  def index
    authorize Post

    # XXX: Cada vez que cambiamos un Post tocamos el sitio con lo que es
    # más simple saber si hubo cambios.
    return unless stale?([current_usuarie, site, filter_params])

    # Todos los artículos de este sitio para el idioma actual
    @posts = site.indexed_posts.where(locale: locale)
    @posts = @posts.page(filter_params.delete(:page)) if site.pagination
    # De este tipo
    @posts = @posts.where(layout: filter_params[:layout]) if filter_params[:layout]
    # Que estén dentro de la categoría
    @posts = @posts.in_category(filter_params[:category]) if filter_params[:category]
    # Aplicar los parámetros de búsqueda
    @posts = @posts.search(locale, filter_params[:q]) if filter_params[:q].present?
    # A los que este usuarie tiene acceso
    @posts = PostPolicy::Scope.new(current_usuarie, @posts).resolve

    # Filtrar los posts que les invitades no pueden ver
    @usuarie = site.usuarie? current_usuarie

    @site_stat = SiteStat.new(site)
  end

  def show
    authorize post
    breadcrumb post.title.value, ''
    fresh_when post
  end

  # Genera una previsualización del artículo.
  def preview
    authorize post

    render html: post.render
  end

  def new
    authorize Post

    layout = site.layouts[pluck_param(:layout).to_sym]
    @post = Post.build(locale: locale, layout: layout, site: site)

    breadcrumb I18n.t('loaf.breadcrumbs.posts.new', layout: layout.humanized_name.downcase), ''
  end

  def create
    authorize Post
    service = PostService.new(site: site,
                              usuarie: current_usuarie,
                              params: params)
    @post = service.create_or_update

    if post.persisted?
      site.touch
      forget_content
    end

    # @todo Enviar la creación a otro endpoint para evitar tantas
    # condiciones.
    if htmx?
      if post.persisted?
        triggers = { 'notification:show' => { 'id' => pluck_param(:saved, optional: true) } }

        swap_modals(triggers)

        @value = post.title.value
        @uuid = post.uuid.value
        @name = pluck_param(:name)

        render render_path_from_attribute, layout: false
      else
        headers['HX-Retarget'] = "##{pluck_param(:form)}"
        headers['HX-Reswap'] = 'outerHTML'

        render 'posts/form', layout: false, post: post, site: site, **params.permit(:form, :base, :dir, :locale)
      end
    elsif post.persisted?
      redirect_to site_post_path(site, post)
    else
      render 'posts/new'
    end
  end

  def edit
    authorize post
    breadcrumb post.title.value, site_post_path(site, post, locale: locale), match: :exact
    breadcrumb 'posts.edit', ''
  end

  # Este endpoint se encarga de actualizar el post. Si el post se edita
  # desde el formulario principal, re-renderizamos el formulario si hay
  # errores o enviamos a otro lado al guardar.
  #
  # Si los datos llegaron por HTMX, hay que regenerar el formulario
  # y reemplazarlo en su modal (?) o responder con su tarjeta para
  # reemplazarla donde sea que esté.
  #
  # @todo la re-renderización del formulario no es necesaria si tenemos
  # validación client-side.
  def update
    authorize post

    service = PostService.new(site: site,
                              post: post,
                              usuarie: current_usuarie,
                              params: params)

    if service.update.persisted?
      site.touch
      forget_content
    end

    if htmx?
      if post.persisted?
        triggers = { 'notification:show' => pluck_param(:saved, optional: true) }

        swap_modals(triggers)

        @value = post.title.value
        @uuid = post.uuid.value

        if (result_id = pluck_param(:result_id, optional: true))
          headers['HX-Retarget'] = "##{result_id}"
          headers['HX-Reswap'] = 'outerHTML'

          @indexed_post = site.indexed_posts.find_by_post_id(post.uuid.value)

          render 'posts/new_related_post', layout: false
        # @todo Confirmar que esta ruta no esté transitada
        else
          @name = pluck_param(:name)

          render render_path_from_attribute, layout: false
        end
      else
        headers['HX-Retarget'] = "##{params.require(:form)}"
        headers['HX-Reswap'] = 'outerHTML'

        render 'posts/form', layout: false, post: post, site: site, **params.permit(:form, :base, :dir, :locale)
      end
    elsif post.persisted?
      redirect_to site_post_path(site, post)
    else
      render 'posts/edit'
    end
  end

  # Eliminar artículos
  def destroy
    authorize post

    service = PostService.new(site: site,
                              post: post,
                              usuarie: current_usuarie,
                              params: params)

    # TODO: Notificar si se pudo o no
    service.destroy
    site.touch
    redirect_to site_posts_path(site, locale: post.lang.value)
  end

  # Reordenar los artículos
  def reorder
    authorize site

    service = PostService.new(site: site,
                              usuarie: current_usuarie,
                              params: params)

    service.reorder
    site.touch
    redirect_to site_posts_path(site, locale: site.default_locale)
  end

  # Devuelve el idioma solicitado a través de un parámetro, validando
  # que el sitio soporte ese idioma, de lo contrario devuelve el idioma
  # actual.
  #
  # TODO: Debería devolver un error o mostrar una página donde se
  # solicite a le usuarie crear el nuevo idioma y que esto lo agregue al
  # _config.yml del sitio en lugar de mezclar idiomas.
  def locale
    @locale ||= site&.locales&.find(-> { site&.default_locale }) do |l|
      l.to_s == params[:locale]
    end
  end

  # Instruye al editor a olvidarse el contenido del artículo.  Usar
  # cuando hayamos guardado la información correctamente.
  def forget_content
    flash[:js] = { target: 'editor', action: 'forget-content', keys: (params[:storage_keys] || []).to_json }
  end

  private

  # Los parámetros de filtros que vamos a mantener en todas las URLs,
  # solo los que no estén vacíos.
  #
  # @return [Hash]
  def filter_params
    @filter_params ||= params.permit(:q, :category, :layout, :page).to_hash.select do |_, v|
      v.present?
    end.transform_keys(&:to_sym)
  end

  def post
    @post ||= site.indexed_posts.find_by!(locale: locale, path: params[:post_id] || params[:id]).post
  end

  # Recuerda el nombre del servicio de subida de archivos
  def service_for_direct_upload
    session[:service_name] = site.name.to_sym
  end

  # @param triggers [Hash] Otros disparadores
  def swap_modals(triggers = {})
    params.permit(:show, :hide).each_pair do |key, value|
      triggers["modal:#{key}"] = { id: value } if value.present?
    end

    headers['HX-Trigger'] = triggers.to_json if triggers.present?
  end

  # @return [String]
  def render_path_from_attribute
    case pluck_param(:attribute)
    when 'new_has_many' then 'posts/new_has_many_value'
    when 'new_belongs_to' then 'posts/new_belongs_to_value'
    when 'new_has_and_belongs_to_many' then 'posts/new_has_many_value'
    when 'new_has_one' then 'posts/new_has_one_value'
    else 'nothing'
    end
  end
end

app/views/posts/attributes/_color.haml
.form-group
  = label_tag "#{base}_#{attribute}", post_label_t(attribute, post: post)
  = color_field base, attribute, value: metadata.value,
    **field_options(attribute, metadata)
  = render 'posts/attribute_feedback',
    post: post, attribute: attribute, metadata: metadata

app/views/posts/attributes/_created_at.haml
-# nada

app/views/posts/attributes/_email.haml
.form-group
  = label_tag "#{base}_#{attribute}", post_label_t(attribute, post: post)
  = email_field base, attribute, value: metadata.value,
    **field_options(attribute, metadata)
  = render 'posts/attribute_feedback',
    post: post, attribute: attribute, metadata: metadata

app/views/posts/attributes/_file.haml
.form-group{ data: { controller: 'file-preview' } }
  = label_tag "#{base}_#{attribute}", post_label_t(attribute, post: post)

  - if metadata.static_file
    - case metadata.static_file.blob.content_type
      - when %r{\Avideo/}
        = video_tag url_for(metadata.static_file),
          controls: true, class: 'img-fluid',
          data: { 'file-preview-target': 'preview' }
      - when %r{\Aaudio/}
        = audio_tag url_for(metadata.static_file),
          controls: true, class: 'img-fluid',
          data: { 'file-preview-target': 'preview' }
      - when 'application/pdf'
        %iframe{ src: url_for(metadata.static_file) }
      - else
        = link_to t('posts.attribute_ro.file.download'),
          url_for(metadata.static_file)
    -# Mantener el valor si no enviamos ninguna imagen
    = hidden_field_tag "#{base}[#{attribute}][path]", metadata.value['path']
    -# Los archivos requeridos solo se pueden reemplazar
    - unless metadata.required
      .custom-control.custom-switch
        = check_box_tag "#{base}[#{attribute}][path]", '', false, id: "#{base}_#{attribute}_destroy", class: 'custom-control-input'
        = label_tag "#{base}_#{attribute}_destroy", t('posts.attributes.file.destroy'), class: 'custom-control-label'

  .custom-file
    = file_field(*field_name_for(base, attribute, :path),
      **field_options(attribute, metadata, required: (metadata.required && !metadata.path?)),
      class: "custom-file-input #{invalid(post, attribute)}",
      lang: locale,
      data: { 'file-preview-target': 'input', action: 'file-preview#update' })
    = label_tag "#{base}_#{attribute}_path",
      post_label_t(attribute, :path, post: post), class: 'custom-file-label'
    = render 'posts/attribute_feedback',
      post: post, attribute: [attribute, :path], metadata: metadata

.form-group
  = label_tag "#{base}_#{attribute}_description",
    post_label_t(attribute, :description, post: post, required: false)
  = text_field(*field_name_for(base, attribute, :description),
    value: metadata.value['description'],
    dir: dir, lang: locale,
    **field_options(attribute, metadata, required: false))
  = render 'posts/attribute_feedback',
    post: post, attribute: [attribute, :description], metadata: metadata

app/views/posts/attributes/_lang.haml
= hidden_field_tag "#{base}[lang]", post&.lang&.value

app/views/posts/attributes/_locales.haml
- if site.locales.count > 1
  %fieldset
    %legend= post_label_t(attribute, post: post)

    = render 'posts/attribute_feedback',
      post: post, attribute: attribute, metadata: metadata

    - site.locales.each do |locale|
      - next if locale == post.locale.value
      - locale_t = t("locales.#{locale}.name", default: locale.to_s.humanize)
      - value = metadata.value.find do |v|
        - metadata.values[locale]&.values&.include?(v)

      .form-group
        = label_tag "#{base}_#{attribute}_#{locale}", locale_t

        = select_tag("#{plain_field_name_for(base, attribute)}[]",
          options_for_select(metadata.values[locale] || {}, value),
          **field_options(attribute, metadata), include_blank: t('.empty'))

app/views/posts/attributes/_markdown.haml
.form-group.markdown-content
  = label_tag "#{base}_#{attribute}", post_label_t(attribute, post: post)
  = render 'posts/attribute_feedback',
    post: post, attribute: attribute, metadata: metadata
  = text_area_tag "#{base}[#{attribute}]", metadata.value,
    dir: dir, lang: locale,
    **field_options(attribute, metadata, class: 'content')
  .markdown-editor.mt-1

app/views/posts/attributes/_new_belongs_to.haml
-#
  Genera un listado de radios entre los que se puede elegir solo uno para
  guardar.  Podemos elegir entre los artículos ya cargados o agregar uno
  nuevo.

  Al agregar uno nuevo, se abre un segundo modal que carga el formulario
  correspondiente vía HTMX. El formulario tiene que cargarse por fuera
  del formulario principal porque no se pueden anidar.

:ruby
  id = random_id
  name = "#{base}[#{attribute}]"
  form_id = random_id
  modal_id = random_id
  post_id = random_id
  post_form_id = random_id
  post_modal_id = random_id
  post_form_loaded_id = random_id
  value_list_id = random_id
  controllers = %w[modal array]
  controllers << 'required-checkbox' if metadata.required

%div{ id: modal_id, data: { controller: controllers.join(' '), 'array-original-value': metadata.value.to_json, 'array-new-array-value': site_posts_new_related_post_path(site) } }
  %template{ data: { 'array-target': 'placeholder' } }
    .col.p-3{ 'aria-hidden': 'true' }
      %span.placeholder.w-100

  .form-group
    .d-flex.align-items-center.justify-content-between
      %div
        = label_tag id, post_label_t(attribute, post: post), class: 'mb-0'
        = render 'posts/required_checkbox', required: metadata.required, name: name, initial: metadata.empty?, type: 'radio'
      = render 'bootstrap/btn', content: t('.edit'), action: 'modal#show'

  -# Mostramos la lista de valores actuales.

    Al aceptar el modal, se vacía el listado y se completa en base a
    renderizaciones con HTMX. Para poder hacer eso, tenemos que poder
    acceder a todos los items dentro del modal (como array.item) y
    enviar el valor al endpoint que devuelve uno por uno. Esto lo
    tenemos disponible en Stimulus, pero queremos usar HTMX o técnica
    similar para poder renderizar del lado del servidor.

    Para poder cancelar, mantenemos el estado original y desactivamos
    o activamos los ítemes según estén incluidos en esa lista o no.
  .row.no-gutters.placeholder-glow{ data: { 'array-target': 'current' } }
    -# @todo issue-7537
    - if !metadata.empty? && (indexed_post = site.indexed_posts.find_by(post_id: metadata.value))
      = render 'posts/new_related_post', post: indexed_post, attribute: metadata.type, inverse: metadata.inverse

  = render 'bootstrap/modal', id: id, modal_content_attributes: { class: 'h-100' }, hide_actions: ['array#cancel'], keydown_actions: %w[keydown->array#cancelWithEscape] do
    - content_for :"#{id}_header" do
      .form-group.flex-grow-1.mb-0
        = label_tag id, post_label_t(attribute, post: post)
        %input.form-control{ data: { 'array-target': 'search', action: 'input->array#search' }, type: 'search', placeholder: t('.filter') }

    - content_for :"#{id}_body" do
      .form-group.mb-0{ id: value_list_id }
        - metadata.values.each do |(value, uuid, disabled)|
          = render 'targets/array/item', value: uuid, 'send-value': uuid, 'human-value': value, class: 'mb-2' do
            = render 'bootstrap/custom_checkbox', name: name, id: random_id, value: uuid, checked: metadata.value.include?(uuid), content: value, type: 'radio', disabled: disabled do
              = t('posts.attributes.new_belongs_to.disabled') if disabled

    -#
      Según la definición del campo, si hay un filtro, tenemos que poder
      elegir qué tipo de esquema queremos o si hay uno solo, siempre
      vamos a enviar ese. Si no hay ninguno, tendríamos que poder elegir
      entre todos los esquemas.

    - content_for :"#{id}_footer" do
      - layout = metadata.filter[:layout]
      - if layout.is_a?(String)
        %input{ type: 'hidden', name: 'layout', value: layout, form: post_form_id }
        = render 'bootstrap/btn', content: t('.add', layout: site.layouts[layout].humanized_name), form: post_form_id, type: 'submit', class: 'm-0 mr-1'
      - else
        - layouts   = layout&.map { |x| site.layouts[x] }
        - layouts ||= site.layouts.values
        .input-group.w-auto.flex-grow-1.my-0
          %select.form-control{ form: post_form_id, name: 'layout' }
            - layouts.each do |layout|
              %option{ value: layout.name }= layout.humanized_name
          .input-group-append
            = render 'bootstrap/btn', content: t('.add', layout: ''), form: post_form_id, type: 'submit', class: 'mb-0 mr-0'
      = render 'bootstrap/btn', content: t('.accept'), action: 'array#accept modal#hide', class: 'm-0 mr-1'
      = render 'bootstrap/btn', content: t('.cancel'), action: 'array#cancel modal#hide', class: 'm-0'

-#
  Este segundo modal es el que carga los formularios de
  creación/modificación de artículos relacionados. Se envía a post_form
  para que sea externo al formulario actual.
- content_for :post_form do
  %form{ id: post_form_id, 'hx-get': site_posts_form_path(site), 'hx-target': "##{post_form_loaded_id}" }
    %input{ type: 'hidden', name: 'show', value: post_modal_id }
    %input{ type: 'hidden', name: 'hide', value: modal_id }
    %input{ type: 'hidden', name: 'target', value: value_list_id }
    %input{ type: 'hidden', name: 'swap', value: 'beforeend' }
    %input{ type: 'hidden', name: 'base', value: id }
    %input{ type: 'hidden', name: 'name', value: name }
    %input{ type: 'hidden', name: 'form', value: form_id }
    %input{ type: 'hidden', name: 'attribute', value: metadata.type }
    - if metadata.inverse?
      %input{ type: 'hidden', name: 'inverse', value: metadata.inverse }
      %input{ type: 'hidden', name: metadata.inverse, value: post.uuid.value }
  %div{ id: post_modal_id, data: { controller: 'modal' } }
    = render 'bootstrap/modal', id: post_id, modal_content_attributes: { class: 'h-100' } do
      - content_for :"#{post_id}_body" do
        %div{ id: post_form_loaded_id }
      - content_for :"#{post_id}_footer" do
        = render 'bootstrap/btn', form: form_id, content: t('.save'), type: 'submit'
        -# @todo: Volver al otro modal
        = render 'bootstrap/btn', content: t('.cancel'), action: 'modal#hide'

app/views/posts/attributes/_permalink.haml
- unless post.new?
  .form-group
    = label_tag "#{base}_#{attribute}", post_label_t(attribute, post: post)
    = text_field base, attribute, value: metadata.value,
      dir: dir, lang: locale,
      **field_options(attribute, metadata)
    = render 'posts/attribute_feedback',
      post: post, attribute: attribute, metadata: metadata